matrix:
  include:
    - os: linux
      sudo: required
      dist: focal
      compiler: gcc
    - os: osx
      osx_image: xcode10.3

language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; sudo apt-get install -y libtbb-dev g++-10 gcc-10 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 ; sudo update-alternatives --set gcc /usr/bin/gcc-10 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tbb ; fi
  - MY_LOCATION=`pwd`
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories/
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - MY_LOCATION=`pwd`
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - cd quicky_tools/setup
  - . setup.sh
  - cd $MY_LOCATION
  - chmod a+x repositories/quicky_tools/bin/*
  - mkdir build
  - cd build

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir quicky_tools; cd quicky_tools; generate_makefile EXT_tbb ; make; ./bin/EXT_tbb.exe ; cd .. ; fi
  - mkdir cmake
  - cd cmake
  - cmake $QUICKY_REPOSITORY/EXT_tbb
  - make
  - ./test_EXT_tbb
#EOF
